### ISSUE TITLE
Container crashes before running 

### ISSUE THREAD

**Issue by AlexiosK95** [st-ing/61850-sim#1]
Hello,
I have pulled the container without any problems but I get some error messages when it's starting. I have tried the examples from the README and also loading my own *.scd file but it exits with the following status:

`collect2: error: ld returned 1 exit status
Preparing simulation...
Running simulation...
chmod: /opt/61850-sim: No such file or directory
/usr/bin/docker-entrypoint: exec: line 38: /opt/61850-sim: not found
`

I have attached the full trace, I'm not sure if the command is not correctly passed or a code error.
[errortrace.txt](https://github.com/st-ing/61850-sim/files/12410314/errortrace.txt)

Greetings
Alex

**Comment by dusanstojkovic** [comment]
Hi Alex,

It looks to me that your SCD file is not mapped correctly. (i.e. I get the same error if I misspell the filename).

Check the the path, filename and permission.

Cheers
